### ISSUE TITLE
Do authmilter.org tests need real dns?

### ISSUE THREAD

**Issue by dlucredativ** [marcbradshaw/mail-dkim#12]
There are tests using queries against `authmilter.org`, which is not included in `FAKE_DNS.dat`. Is this on purpose?

**Comment by marcbradshaw** [comment]
Hi,

I see that domain in 3 test files.

2 of them are real lookups, and are guarded by a Test::RequiresInternet, so if the testing system does not have internet access those tests will be skipped.

The third is a parse test, which does not require a query, so should work when internet access it not available.

**Comment by dlucredativ** [comment]
Unfortunately, while Debian's Salsa Gitlab environment allows outbound http(s) for CI/CD, it does not allow DNS queries. As a result, the autopkgtest of `libmail-dkim-perl` fails producing errors like:
```
DNS query timeout for key1._domainkey.test.authmilter.org at /usr/share/perl5/Mail/DKIM/DNS.pm line 100.
```
Do you have a suggestion how to make those tests succeed?
